### ISSUE TITLE
Question: How do I share code between doctest blocks?

### ISSUE THREAD

**Issue by EmilStenstrom** [tmarktaylor/phmdoctest#28] opened 2022-04-30 07:49 UTC
Thanks for writing this library and releasing it for free to the world! :)

I think I misunderstand something fundamental, but I've tried various combinations for an hour now, and would appreciate some simple pointers if you have the time. I'd like to generate a test setup for a python library called conllu. The readme examples are  incrementally adding variables as the [tutorial in the readme](https://github.com/EmilStenstrom/conllu/) goes on. So pretty much all doctests are thought of as being in the global scope.

Problem is, I can't get things to be shared between the code blocks. Even with this simple example:

In test.md:
``````
```python
from conllu import parse
```

```python
>>> sentences = parse()
```
``````

Generated test.py file:
``````
"""pytest file built from test.md"""

def test_code_2():
    from conllu import parse

def session_00001_line_6():
    r"""
    >>> sentences = parse()
    """
``````

```bash
$ pytest --doctest-modules test.py
================================================= test session starts ==================================================
platform linux -- Python 3.9.1, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/emilstenstrom/Projects/conllu
collected 2 items

test.py F.                                                                                                       [100%]

======================================================= FAILURES =======================================================
_________________________________________ [doctest] test.session_00001_line_6 __________________________________________
011
012     >>> sentences = parse()
UNEXPECTED EXCEPTION: NameError("name 'parse' is not defined")
Traceback (most recent call last):
  File "/home/emilstenstrom/.pyenv/versions/3.9.1/lib/python3.9/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest test.session_00001_line_6[0]>", line 1, in <module>
NameError: name 'parse' is not defined
/home/emilstenstrom/Projects/conllu/test.py:12: UnexpectedException
=============================================== short test summary info ================================================
FAILED test.py::test.session_00001_line_6
============================================= 1 failed, 1 passed in 0.02s ==============================================
```

I'd found the shared-names directive, but the don't seem to work for my case at all:

In test.md:
``````
<!--phmdoctest-share-names-->
```python
from conllu import parse
```

```python
>>> sentences = parse()
```
``````

Generated test.py file:
``````
"""pytest file built from test.md"""
import pytest

from phmdoctest.fixture import managenamespace

def test_code_3(managenamespace):
    from conllu import parse
    managenamespace(operation="update", additions=locals())

def session_00001_line_7():
    r"""
    >>> sentences = parse()
    """
``````

```bash
$ pytest --doctest-modules test.py
================================================= test session starts ==================================================
platform linux -- Python 3.9.1, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/emilstenstrom/Projects/conllu
collected 2 items

test.py F.                                                                                                       [100%]

======================================================= FAILURES =======================================================
_________________________________________ [doctest] test.session_00001_line_7 __________________________________________
015
016     >>> sentences = parse()
UNEXPECTED EXCEPTION: NameError("name 'parse' is not defined")
Traceback (most recent call last):
  File "/home/emilstenstrom/.pyenv/versions/3.9.1/lib/python3.9/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest test.session_00001_line_7[0]>", line 1, in <module>
NameError: name 'parse' is not defined
/home/emilstenstrom/Projects/conllu/test.py:16: UnexpectedException
=============================================== short test summary info ================================================
FAILED test.py::test.session_00001_line_7
============================================= 1 failed, 1 passed in 0.02s ==============================================
```

Tried the setup directive instead, with same result.

Could you help me get this working? Thanks in advance!

**Comment by tmarktaylor** [comment] 2022-04-30 23:59
phmdoctest can use one fenced code block to specify setup for doctests.

To do setup for doctests:

- Put the `<!--phmdoctest-setup-->` directive on the fenced code block with the python setup code.
- pass the option `--setup-doctest` to phmdoctest on the command line when generating the test file.
- `<!--phmdoctest-share-names-->` won't help set up doctests.
- There can only be one  `<!--phmdoctest-setup-->` in a markdown file. It looks like your use case needs more than one.

A working example is [test_setup_doctest.py](https://github.com/tmarktaylor/phmdoctest/blob/master/doc/test_setup_doctest.py)

There are a couple of [Hints](https://tmarktaylor.github.io/phmdoctest/#hints) for doctests.

A new feature could be added to phmdoctest that appends all the doctests together in the generated test file in one long docstring in a single test case.

**Comment by EmilStenstrom** [comment] 2022-05-01 08:39
Thanks for the quick reply. Then it seems this kind of "tutorial style" examples are not a great fit for phmdoctest.

For this use-case, I think the best fit would be a mode where all doctests run in the global scope, mutating the same variables continuously. The good thing about having separate test cases per doctest is that I can pass pytest `-x` and clearly see which test has failed, instead of looking through a dump of my full README.

I can see if you think this is out of scope for phmdoctest! If this is something you'd be interested in adding, I'm happy to help getting it done if I can.

**Comment by tmarktaylor** [comment] 2022-05-01 13:52
There should not be the need to look through a lot of test output to find the source of the error.

Here is an example showing roughly what a single long docstring would look like:

To reproduce the example:
- checkout phmdoctest
- make a folder test2.
- copy doc/test_setup_doctest.py to test2.

Append the code below to bottom of a test2/test_setup_doctest.py and run this command. It simulates a test file generated with the proposed feature to combine the Python interactive sessions.

`pytest -v test2/test_setup_doctest.py --doctest-modules`

```python
# todo- delete experimental
def session_00999_should_be_last():
    r"""
    >>> # line 50 from md file
    >>> mylist
    [1, 2, 3, 55]
    >>> import math
    >>> mylist.clear()
    >>> mylist.append(55)
    >>> mylist
    [55]
    >>> # line 80 from md file
    >>> import math
    >>> mylist.append(56)
    >>> mylist
    [55, 56]
    >>> # line 110 from md file
    >>> # "a" + mylist.append(56)  # uncomment to simulate unexpected exception
    >>> # line 140 from md file
    >>> mylist
    [55, 56, "not expected"]
    >>> # line 170 from md file
    >>> mylist.append(57)
    >>> mylist
    [55, 56, 57]
    >>> # line 210 from md file
    >>> mylist.append(58)
    >>> mylist
    [55, 56, 57, 58, 59]
    """
```

```
rootdir: C:\Users\code\Documents\mark\v1, configfile: pyproject.toml
plugins: phmdoctest-1.0.0
collected 7 items

test2/test_setup_doctest.py::test_setup_doctest.session_00000 PASSED                        [ 14%]
test2/test_setup_doctest.py::test_setup_doctest.session_00001_line_69 PASSED                [ 28%]
test2/test_setup_doctest.py::test_setup_doctest.session_00002_line_76 PASSED                [ 42%]
test2/test_setup_doctest.py::test_setup_doctest.session_00999_should_be_last FAILED         [ 57%]
test2/test_setup_doctest.py::test_code_20_output_27 PASSED                                  [ 71%]
test2/test_setup_doctest.py::test_code_37_output_42 PASSED                                  [ 85%]
test2/test_setup_doctest.py::test_code_47_output_51 PASSED                                  [100%]

============================================ FAILURES ============================================
___________________ [doctest] test_setup_doctest.session_00999_should_be_last ____________________
109     [55]
110     >>> # line 80 from md file
111     >>> import math
112     >>> mylist.append(56)
113     >>> mylist
114     [55, 56]
115     >>> # line 110 from md file
116     >>> # "a" + mylist.append(56)  # uncomment to simulate unexpected exception
117     >>> # line 140 from md file
118     >>> mylist
Expected:
    [55, 56, "not expected"]
Got:
    [55, 56]

C:\Users\code\Documents\mark\v1\test2\test_setup_doctest.py:118: DocTestFailure
==================================== short test summary info =====================================
FAILED test2/test_setup_doctest.py::test_setup_doctest.session_00999_should_be_last
================================== 1 failed, 6 passed in 0.11s ===================================
```

Look at the test case `session_00999_should_be_last`. Pytest's doctest stopped at the first failure. It would keep going if given the option `--doctest-continue-on-failure`.

The proposed feature for phmdoctest would put in a comment giving the line number in the .md file where it found the Python interactive session. `117     >>> # line 140 from md file` appearing just above the end of the output points to the source of the failure.

Keep in mind all of pytest's options for doctests can be used on the test file. See the section titled ` Using ‘doctest’ options` in the pytest docs.

Additionally Python's [doctest directives](https://docs.python.org/3/library/doctest.html#directives) can be placed inline in the Python interactive sessions in the Markdown.

**Comment by tmarktaylor** [comment] 2022-05-02 12:55
A pull request to add the feature to share code between doctest blocks is welcome.

- see CONTRIBUTING.md.
- There should not be any new warnings produced by the inspect: job of .github/workflows/ci.yml.
- There should not be any new phmdoctest command line options.
- This means the feature should be activated by new HTML comment directive(s) placed on a fenced code block containing the Python interactive session. Directives start with `<!--phmdoctest-`. This is a suggestion, not a requirement.
- pytest-phmdoctest is dependent on phmdoctest. The feature should work when the phmdoctest is invoked by pytest-phmdoctest (docmod or generate modes).
- When a generated test fails in pytest, the output should indicate which fenced code block (FCB) in the Markdown file is failing. I show an example of this above with `# line 110 from md file`.  We already know the file name from the test file docstring so we just need to locate the start of the FCB.
- The FCB can have a `<!--phmdoctest-label IDENTIFIER-->` directive which will change the name of generated test function.
- Consider the tradeoffs of implementing the feature as a separate module that takes a generated test file and rewrites the Python interactive session test cases. Such a module would have a smaller number of lines of code, but would require extra steps to use. I personally favor ease of use over development effort.
- Sorry in advance for requirements I didn't mention above.

**Comment by EmilStenstrom** [comment] 2022-05-02 20:50
Thank you for the detailed explanation, requirements, and pointers. Even with your suggestions, this is a large project for me.

I don't have a lot of time to hack on open source between a full time job and two small children, but I'll keep this project in mind for when I do. My current "solution" to testing the readme is hacked together with duct-tape and doesn't work locally in Python 3.6-3.7, so I AM motivated to fix it. We'll see if I find the time.

**Comment by tmarktaylor** [comment] 2022-06-04 18:35
Try this:
- make a copy of README.md.
- Replace all the Markdown closing fences (triple back tick) with newline so that they are now empty lines.
- This terminates the ">>>" examples with blank lines so doctest can test them directly.
- Call Python standard library `doctest.testfile()` with the updated README.md. In Simple Usage: Checking Examples in a Text File: "... the file content is treated as if it were a single giant docstring."

Thanks for starting the conversation. It gave me some ideas for new features.

**Comment by EmilStenstrom** [comment] 2022-06-06 12:45
This actually worked great (with some caveats because of funcy dict formatting). This is how I do it now! https://github.com/EmilStenstrom/conllu/blob/master/tests/test_readme.py

**Closed as completed** 2022-06-11 13:17 UTC
Labels: enhancement
